import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
        <Link href="/list/list1">
          LIST1 (useEffect)
        </Link>
        <br/>
        <Link href="/list/list2">
          LIST2 (getStaticProps)
        </Link>
        <br/>
        <Link href="/list/list3">
          LIST3 (getServerSideProps)
        </Link>
        <br/>
        </div>
      </main>
    </>
  )
}
