server:
  port: 80
  servlet:
    session:
      timeout : 1800  #1800초(30분)
  
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소
      
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
