server:
  port: 9001
  type: local
  servlet:
    context-path: /
    session:
      cookie:
        name: AUTHSESSIONID
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
  # 프록시 환경에서 사용
  forward-headers-strategy: NATIVE
  
mybatis:
  mapper-locations: classpath:mapper/**/**.xml
  config-location: classpath:mybatis-config.xml

frontend:
  custom:
    add:
      static:
        location: /api/imagePath/**
        file:
          path: C://imagePath/

spring:
  session:
    redis:
      flush-mode: on-save
      namespace: bauth-local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
  config:
    import: vault://
  cloud:
    vault:
      config.lifecycle:
        enabled: true
        min-renewal: 10s
        expiry-threshold: 5m
#        lease-endpoints: SysLeases
      uri: https://vlt.bluetype.win
      host: vlt.bluetype.win
      port: 443
      scheme: https                  
      connection-timeout: 5000
      read-timeout: 15000
      
      authentication: TOKEN
      
      token: 
      kv:
        enabled: true
        backend: kv
        profile-separator: '/'
        default-context: apps05
        application-name: apps05
        profiles: local
      database:
        enabled: true
        role: dev-33005
        #role: dev-33001
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://pf201.bluetype.net:33005/app_database?serverTimezone=UTC&useLegacyDatetimeCode=false&allowMultiQueries=true
    #url: jdbc:mariadb://pf201.bluetype.net:33001/app_database?characterEncoding=UTF-8
    username:
    password:
    hikari:
      pool-name: hikari-primary
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
      validation-timeout: 2000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate 
      #validate: 엔티티와 테이블이 정상 매핑되었는지만 확인 , 
      #create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
      #update: 변경분만 반영
    properties:
      hibernate:
        '[format_sql]': true
        '[show_sql]': false
#        '[show_sql]': true
        '[id.db_structure_naming_strategy]': legacy
  data:
    redis:
      host: pf201.bluetype.net    
      #port: 24079
      port: 63005
      password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@bluetype.net
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            client-secret: 
            redirect-uri: http://127.0.0.1:9001/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: account_email
          naver:
            #client-id: T8ff02ymO8ervWJ5dd4x
            #client-secret: EQCemI_egs
            client-id: 
            client-secret: 
            redirect-uri: http://127.0.0.1:9001/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
          google:
            client-id: 
            client-secret: 
            redirect-uri: http://127.0.0.1:9001/login/oauth2/code/google
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#sms.gabia.com 문자전송 (건당 전송요금 발생)
gabia:
  smsId: 
  smsKey:
  callback: 0262381500
        
#mybatis:  
#  type-aliases-package: com.narui.bauth.**.dto
#  mapper-locations: /mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: null

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    csrf:
      enabled: true
  cache:
    disabled: true
        
        
        
logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss}}){faint}%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    jdbc:
      audit: off
      resultset: off
      resultsettable: info
      sqlonly: off
      sqltiming: info
      connection: off
    root: debug
    '[org.springframework]': info
    '[org.springframework.beans]': info
    '[org.springframework.data]': debug
    '[org.springframework.data.redis]': info
    '[org.springframework.boot.autoconfigure]': info
    '[org.springframework.session.web]': info
    '[org.springframework.security.jackson2]': info
    '[org.hibernate]': info
    '[org.hibernate.orm]': info
    '[org.hibernate.orm.jdbc.bind]': trace
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type]': info    
    '[org.apache]': info
    '[io.lettuce]': info
    '[io.netty]': info
    '[sun.rmi]': info
    '[javax.management]': info
    '[javax.activation]': info
    '[com.zaxxer]': info
    '[org.thymeleaf]': info
    '[com.narui.bauth]': debug
    '[com.narui.common]': debug
    '[_org.springframework.web.servlet.HandlerMapping.Mappings]': info    
    '[org.mariadb.jdbc]': info
    '[angus.activation]': info
    '[jakarta.activation]': info
    '[io.swagger]': info
    '[jdk.internal.httpclient.debug]': info    
    
jwt:
  key: inittest
  #spring.security.oauth2.client.provider.naru-oidc-provider.issuer-uri 와
  #spring.security.oauth2.resourceserver.jwt.issuer-uri 에서 호출하는 값
  issuer-uri: http://127.0.0.1:9001
  #issuer-uri: https://lc232.bluetype.win

signin-uri: /user/auth/identifier
